extends SceneTree

const Reglas = preload("res://scripts/reglas_pool.gd")
var fallos := 0

func _initialize() -> void:
	create_timer(20).timeout.connect(func(): quit(2))
	call_deferred("_probar")

func comprobar(condicion: bool, mensaje: String) -> void:
	if not condicion:
		fallos += 1
		push_error(mensaje)

func mesa_abierta():
	var r = Reglas.new()
	r.saque = false
	return r

func asignada():
	var r = mesa_abierta()
	r.grupos = [Reglas.Grupo.LISAS, Reglas.Grupo.RAYADAS]
	return r

func _probar() -> void:
	var r = Reglas.new()
	r.iniciar_tiro()
	r.contacto(1)
	r.retirar(3, true)
	var resultado = r.finalizar_tiro()
	comprobar(r.turno == 1 and r.grupos == [0, 0], "El saque no asigna grupos y embocar conserva turno")
	comprobar(not resultado.bola_en_mano, "Saque con bola embocada válido")
	r.iniciar_tiro()
	r.contacto(9)
	r.retirar(9, true)
	r.finalizar_tiro()
	comprobar(r.grupos == [2, 1] and r.turno == 1, "Primera bola legal asigna grupos opuestos")
	r.iniciar_tiro()
	r.contacto(10)
	r.banda(0)
	r.finalizar_tiro()
	comprobar(r.turno == 2, "Un tiro válido sin embocar cambia turno")
	r.iniciar_tiro()
	r.contacto(10)
	r.retirar(2, true)
	resultado = r.finalizar_tiro()
	comprobar(resultado.bola_en_mano and r.turno == 1, "Contacto incorrecto es falta aunque entre una propia")

	r = mesa_abierta()
	r.iniciar_tiro()
	r.contacto(2)
	r.retirar(2, true)
	r.retirar(11, true)
	r.finalizar_tiro()
	comprobar(r.grupos == [1, 2], "Si entran ambos grupos, asignar el primero")
	r = mesa_abierta()
	r.iniciar_tiro()
	r.contacto(1)
	r.retirar(1, true)
	r.retirar(0, true)
	resultado = r.finalizar_tiro()
	comprobar(r.grupos == [0, 0] and resultado.bola_en_mano and r.turno == 2, "Falta no asigna grupos")
	r = mesa_abierta()
	r.iniciar_tiro()
	r.contacto(8)
	r.banda(0)
	comprobar(r.finalizar_tiro().bola_en_mano, "8 primero en mesa abierta es falta")
	for jugador in [1, 2]:
		r = asignada()
		r.turno = jugador
		r.iniciar_tiro()
		r.contacto(1 if jugador == 1 else 9)
		resultado = r.finalizar_tiro()
		comprobar(not resultado.bola_en_mano and r.turno == 3 - jugador, "Contacto propio sin banda ni embocada solo cambia turno")
	r = mesa_abierta()
	r.iniciar_tiro()
	r.contacto(1)
	resultado = r.finalizar_tiro()
	comprobar(not resultado.bola_en_mano and r.turno == 2 and r.grupos == [0, 0], "Sin banda ni embocada mantiene mesa abierta y cambia turno")
	r = asignada()
	r.restantes.assign([8, 9])
	r.iniciar_tiro()
	r.contacto(8)
	resultado = r.finalizar_tiro()
	comprobar(not resultado.bola_en_mano and r.turno == 2 and r.ganador == 0, "Tocar la 8 como objetivo sin embocar ni banda solo cambia turno")
	r = asignada()
	r.iniciar_tiro()
	r.banda(0)
	comprobar(r.finalizar_tiro().bola_en_mano, "Banda sin tocar bola no valida el tiro")
	r = asignada()
	r.iniciar_tiro()
	r.contacto(1)
	r.retirar(9, true)
	resultado = r.finalizar_tiro()
	comprobar(not resultado.bola_en_mano and r.turno == 2, "Embocar rival con primer contacto propio cambia turno sin falta")
	r = asignada()
	r.iniciar_tiro()
	r.contacto(1)
	r.retirar(1, false)
	comprobar(r.finalizar_tiro().bola_en_mano, "Una bola fuera es falta")

	r = Reglas.new()
	r.iniciar_tiro()
	r.contacto(1)
	for n in [1, 2, 3, 4]:
		r.banda(n)
	resultado = r.finalizar_tiro()
	comprobar(not resultado.bola_en_mano and r.turno == 2, "Saque con cuatro bolas distintas en banda")
	r = Reglas.new()
	r.iniciar_tiro()
	r.contacto(1)
	for n in range(4):
		r.banda(1)
	comprobar(r.finalizar_tiro().bola_en_mano, "Cuatro rebotes de la misma bola no validan el saque")
	r = Reglas.new()
	r.iniciar_tiro()
	r.contacto(1)
	r.retirar(8, true)
	r.retirar(0, true)
	comprobar(r.finalizar_tiro().get("reiniciar", false), "8 en saque reinicia incluso con blanca embocada")
	r = asignada()
	r.iniciar_tiro()
	r.contacto(1)
	r.retirar(8, true)
	comprobar(r.finalizar_tiro().ganador == 2, "8 anticipada pierde")
	r = asignada()
	r.restantes.assign([7, 8, 9])
	r.iniciar_tiro()
	r.contacto(7)
	r.retirar(7, true)
	r.retirar(8, true)
	comprobar(r.finalizar_tiro().ganador == 2, "No vale meter última propia y 8 en el mismo tiro")
	r = asignada()
	r.restantes.assign([8, 9])
	r.iniciar_tiro()
	r.contacto(8)
	r.retirar(8, true)
	comprobar(r.finalizar_tiro().ganador == 1, "8 legal gana sin anunciar tronera")
	r = asignada()
	r.restantes.assign([8, 9])
	r.iniciar_tiro()
	r.contacto(8)
	r.retirar(8, true)
	r.retirar(0, true)
	comprobar(r.finalizar_tiro().ganador == 2, "8 y blanca en el mismo tiro pierde")
	r = asignada()
	r.restantes.assign([8, 9])
	r.iniciar_tiro()
	r.contacto(8)
	r.retirar(8, false)
	comprobar(r.finalizar_tiro().ganador == 2, "8 fuera de la mesa pierde")
	# Caso de la captura: J2 ya terminó lisas y mete negra + blanca.
	# El orden de las dos caídas no cambia el ganador ni el motivo.
	for orden in [[8, 0], [0, 8]]:
		r = asignada()
		r.turno = 2
		r.grupos = [2, 1]
		r.restantes.assign([8, 14])
		r.iniciar_tiro()
		r.contacto(8)
		for numero in orden:
			r.retirar(numero, true)
		resultado = r.finalizar_tiro()
		comprobar(resultado.ganador == 1, "J2 pierde con negra y blanca, en cualquier orden")
		comprobar(resultado.mensaje == "El jugador 2 pierde por embocar la negra y la blanca en el mismo tiro.", "Mensaje preciso para negra y blanca")
		comprobar(not resultado.mensaje.contains("antes"), "No atribuir a una 8 anticipada")
	print("REGLAS TEST: ", fallos, " fallos")
	quit(0 if fallos == 0 else 1)
